/**
 * Map common lab label variants (EN + ES) → seeded biomarker ids.
 * Keys are normalized: lowercase, collapsed whitespace, stripped accents/punctuation.
 */

const ALIASES: Record<string, string> = {
  // Lipids
  "total cholesterol": "total-cholesterol",
  "cholesterol total": "total-cholesterol",
  "chol total": "total-cholesterol",
  cholesterol: "total-cholesterol",
  "total-cholesterol": "total-cholesterol",
  "colesterol total": "total-cholesterol",
  colesterol: "total-cholesterol",
  ldl: "ldl-cholesterol",
  "ldl cholesterol": "ldl-cholesterol",
  "ldl chol": "ldl-cholesterol",
  "ldl-c": "ldl-cholesterol",
  "ldl-cholesterol": "ldl-cholesterol",
  "direct ldl": "ldl-cholesterol",
  "calc ldl": "ldl-cholesterol",
  "calculated ldl": "ldl-cholesterol",
  "colesterol ldl": "ldl-cholesterol",
  "colesterol de lipoproteinas de baja densidad": "ldl-cholesterol",
  hdl: "hdl-cholesterol",
  "hdl cholesterol": "hdl-cholesterol",
  "hdl chol": "hdl-cholesterol",
  "hdl-c": "hdl-cholesterol",
  "hdl-cholesterol": "hdl-cholesterol",
  "colesterol hdl": "hdl-cholesterol",
  "colesterol de lipoproteinas de alta densidad": "hdl-cholesterol",
  triglycerides: "triglycerides",
  triglyceride: "triglycerides",
  trigliceridos: "triglycerides",
  triglicerides: "triglycerides",
  "lipoproteina a": "lp-a",
  "lipoprotein a": "lp-a",
  "lp-a": "lp-a",
  "lp(a)": "lp-a",
  lpa: "lp-a",
  "apo b": "apo-b",
  "apo-b": "apo-b",
  apob: "apo-b",
  apolipoprotein: "apo-b",
  "apolipoprotein b": "apo-b",
  "apolipoproteina b": "apo-b",

  // Glucose / metabolic
  glucose: "glucose-fasting",
  "fasting glucose": "glucose-fasting",
  "glucose fasting": "glucose-fasting",
  "glucose, fasting": "glucose-fasting",
  "glucose-fasting": "glucose-fasting",
  "blood glucose": "glucose-fasting",
  "plasma glucose": "glucose-fasting",
  "fasting plasma glucose": "glucose-fasting",
  fpg: "glucose-fasting",
  glucosa: "glucose-fasting",
  "glucosa en ayunas": "glucose-fasting",
  hba1c: "hba1c",
  "hb a1c": "hba1c",
  "hba1c %": "hba1c",
  "hemoglobin a1c": "hba1c",
  "hemoglobina glicosilada": "hba1c",
  "hemoglobina glicada": "hba1c",
  a1c: "hba1c",
  insulin: "insulin",
  insulina: "insulin",
  "fasting insulin": "insulin",
  urea: "urea",
  bun: "urea",
  "blood urea nitrogen": "urea",
  creatinine: "creatinine",
  creatinina: "creatinine",
  egfr: "egfr",
  "e gfr": "egfr",
  "estimated gfr": "egfr",
  "filtrado glomerular": "egfr",
  "tasa de filtracion glomerular": "egfr",
  "uric acid": "uric-acid",
  "acido urico": "uric-acid",
  urate: "uric-acid",
  urato: "uric-acid",
  homocysteine: "homocysteine",
  homocisteina: "homocysteine",

  // Liver
  alt: "alt",
  "alanine aminotransferase": "alt",
  "alt (sgpt)": "alt",
  "alt/sgpt": "alt",
  sgpt: "alt",
  gpt: "alt",
  "alt, gpt": "alt",
  "alt gpt": "alt",
  "alanina aminotransferasa": "alt",
  "alanina-aminotransferasa": "alt",
  ast: "ast",
  "aspartate aminotransferase": "ast",
  "ast (sgot)": "ast",
  sgot: "ast",
  got: "ast",
  "ast, got": "ast",
  "ast got": "ast",
  "aspartato aminotransferasa": "ast",
  "aspartato-aminotransferasa": "ast",
  ggt: "ggt",
  "gamma-gt": "ggt",
  "gamma gt": "ggt",
  "g-gt": "ggt",
  "gamma-glutamiltransferasa": "ggt",
  "gamma glutamiltransferasa": "ggt",
  alp: "alp",
  "alkaline phosphatase": "alp",
  "fosfatasa alcalina": "alp",
  "bilirubin total": "bilirubin-total",
  "total bilirubin": "bilirubin-total",
  bilirrubina: "bilirubin-total",
  "bilirrubina total": "bilirubin-total",
  albumin: "albumin",
  albumina: "albumin",

  // CBC
  hemoglobin: "hemoglobin",
  haemoglobin: "hemoglobin",
  hgb: "hemoglobin",
  hb: "hemoglobin",
  hemoglobina: "hemoglobin",
  hematocrit: "hematocrit",
  hct: "hematocrit",
  hematocrito: "hematocrit",
  rbc: "rbc",
  "red blood cells": "rbc",
  erythrocytes: "rbc",
  hematies: "rbc",
  "red cell count": "rbc",
  wbc: "wbc",
  "white blood cells": "wbc",
  leukocytes: "wbc",
  leucocitos: "wbc",
  platelets: "platelets",
  platelet: "platelets",
  plaquetas: "platelets",
  mcv: "mcv",
  "mean corpuscular volume": "mcv",
  "volumen corpuscular medio": "mcv",
  "volumen corpuscular medio vcm": "mcv",
  vcm: "mcv",
  mch: "mch",
  "mean corpuscular hemoglobin": "mch",
  "hb corpuscular media": "mch",
  "hb corpuscular media hcm": "mch",
  "hb corpuscolar media": "mch",
  "hb corpuscolar media hcm": "mch",
  hbcorpuscolar: "mch",
  "hbcorpuscolar media": "mch",
  hcm: "mch",
  mchc: "mchc",
  "mean corpuscular hemoglobin concentration": "mchc",
  "c hb corpuscular media": "mchc",
  "c hb corpuscular media chcm": "mchc",
  "c hb corpuscolar media": "mchc",
  "c hb corpuscolar media chcm": "mchc",
  chcm: "mchc",
  rdw: "rdw",
  pdw: "pdw",
  esr: "esr",
  "sedimentation rate": "esr",
  "erythrocyte sedimentation rate": "esr",
  "velocidad de sedimentacion globular": "esr",
  "velocidad de sedimentacion globular v.s.g.": "esr",
  "velocidad de sedimentacion globular v.s.g. 2 a hora": "esr-2h",
  vsg: "esr",
  "v.s.g.": "esr",
  "a la primera hora": "esr",
  "a la segunda hora": "esr-2h",
  basophils: "basophils",
  basofilos: "basophils",
  eosinophils: "eosinophils",
  eosinofilos: "eosinophils",
  neutrophils: "neutrophils",
  neutrofilos: "neutrophils",
  segmentados: "neutrophils",
  lymphocytes: "lymphocytes",
  linfocitos: "lymphocytes",
  monocytes: "monocytes",
  monocitos: "monocytes",
  bands: "bands",
  "bandas / cayados": "bands",
  bandas: "bands",
  cayados: "bands",
  myelocytes: "myelocytes",
  mielocitos: "myelocytes",
  metamyelocytes: "metamyelocytes",
  metamielocitos: "metamyelocytes",
  "atypical lymphocytes": "atypical-lymphs",
  "celulas linfomonocitoides": "atypical-lymphs",

  // Iron / vitamins
  iron: "serum-iron",
  "serum iron": "serum-iron",
  sideremia: "serum-iron",
  hierro: "serum-iron",
  transferrin: "transferrin",
  transferrina: "transferrin",
  tibc: "tibc",
  "total iron binding capacity": "tibc",
  "capacidad total de fijacion de hierro": "tibc",
  ferritin: "ferritin",
  ferritina: "ferritin",
  folate: "folate",
  "folic acid": "folate",
  "acido folico": "folate",
  folatos: "folate",
  "vitamin b12": "vitamin-b12",
  "vitamina b12": "vitamin-b12",
  b12: "vitamin-b12",
  cobalamin: "vitamin-b12",
  cobalamina: "vitamin-b12",
  "vitamin d": "vitamin-d",
  "vitamina d": "vitamin-d",
  "vitamina d 25-hidroxicolecalciferol": "vitamin-d",
  "25-hydroxyvitamin d": "vitamin-d",
  "25-hidroxicolecalciferol": "vitamin-d",
  "25 oh vitamin d": "vitamin-d",
  "25 oh d": "vitamin-d",
  "omega 3": "omega-3-index",
  "omega-3": "omega-3-index",
  "omega-3 index": "omega-3-index",
  "indice omega 3": "omega-3-index",

  // Inflammation / hormones
  crp: "crp",
  "c-reactive protein": "crp",
  "c reactive protein": "crp",
  "hs crp": "crp",
  "hs-crp": "crp",
  "high sensitivity crp": "crp",
  "high-sensitivity c-reactive protein": "crp",
  "proteina c reactiva": "crp",
  "proteina c reactiva pcr": "crp",
  pcr: "crp",
  tsh: "tsh",
  thyrotropin: "tsh",
  tirotropina: "tsh",
  "tirotropina tsh": "tsh",
  "free t4": "free-t4",
  "free-t4": "free-t4",
  ft4: "free-t4",
  "t4 libre": "free-t4",
  "free t3": "free-t3",
  "free-t3": "free-t3",
  ft3: "free-t3",
  "t3 libre": "free-t3",
  cortisol: "cortisol",
  testosterone: "testosterone",
  testosterona: "testosterone",
  "free testosterone": "free-testosterone",
  "testosterona libre": "free-testosterone",
  shbg: "shbg",
  "sex hormone binding globulin": "shbg",
  estradiol: "estradiol",
  "dhea s": "dhea-s",
  "dhea-s": "dhea-s",
  dheas: "dhea-s",
  fsh: "fsh",
  lh: "lh",
  prolactin: "prolactin",
  prolactina: "prolactin",
  psa: "psa",
  "prostate specific antigen": "psa",
  "antigeno prostatico": "psa",
};

export function normalizeMarkerKey(name: string): string {
  return name
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    // CamelCase lab OCR: "HbCorpuscolar" → "Hb Corpuscolar"
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .toLowerCase()
    .replace(/[_/]+/g, " ")
    // Periods matter for "C. Hb … (CHCM)" — treat as separators
    .replace(/[()[\],:;.]+/g, " ")
    // Italian / OCR spelling → English alias keys
    .replace(/\bcorpuscolar\b/g, "corpuscular")
    .replace(/\bhbcorpuscular\b/g, "hb corpuscular")
    .replace(/\s+/g, " ")
    .trim();
}

export function resolveBiomarkerId(name: string): string | null {
  const key = normalizeMarkerKey(name);
  if (!key) return null;
  if (ALIASES[key]) return ALIASES[key];

  // Strip trailing LOINC-ish bracket content already removed; try prefix before "srm"
  const beforeSrm = key.split(/\bsrm\b/)[0]?.trim();
  if (beforeSrm && beforeSrm !== key && ALIASES[beforeSrm]) {
    return ALIASES[beforeSrm];
  }

  // Prefer longer aliases to avoid "hdl" matching inside longer unrelated strings poorly
  const aliases = Object.entries(ALIASES).sort((a, b) => b[0].length - a[0].length);
  for (const [alias, id] of aliases) {
    if (alias.length < 3) continue;
    if (key === alias || key.startsWith(`${alias} `) || key.includes(` ${alias} `)) {
      return id;
    }
    if (key.includes(alias) && alias.length >= 5) return id;
  }
  return null;
}

/** Canonical English display names for confirm screen + report cards */
export const CANONICAL_MARKER_NAMES: Record<string, string> = {
  "total-cholesterol": "Total Cholesterol",
  "ldl-cholesterol": "LDL Cholesterol",
  "hdl-cholesterol": "HDL Cholesterol",
  triglycerides: "Triglycerides",
  "apo-b": "ApoB",
  "lp-a": "Lipoprotein(a)",
  "glucose-fasting": "Fasting Glucose",
  hba1c: "HbA1c",
  insulin: "Insulin",
  urea: "Urea",
  creatinine: "Creatinine",
  egfr: "eGFR",
  "uric-acid": "Uric Acid",
  alt: "ALT",
  ast: "AST",
  ggt: "GGT",
  alp: "ALP",
  "bilirubin-total": "Total Bilirubin",
  albumin: "Albumin",
  hemoglobin: "Hemoglobin",
  hematocrit: "Hematocrit",
  rbc: "Red Blood Cells",
  wbc: "White Blood Cells",
  platelets: "Platelets",
  mcv: "MCV",
  mch: "MCH",
  mchc: "MCHC",
  rdw: "RDW",
  pdw: "PDW",
  esr: "ESR (1st hour)",
  "esr-2h": "ESR (2nd hour)",
  basophils: "Basophils",
  eosinophils: "Eosinophils",
  neutrophils: "Neutrophils",
  lymphocytes: "Lymphocytes",
  monocytes: "Monocytes",
  bands: "Band Neutrophils",
  myelocytes: "Myelocytes",
  metamyelocytes: "Metamyelocytes",
  "atypical-lymphs": "Atypical Lymphocytes",
  "serum-iron": "Serum Iron",
  transferrin: "Transferrin",
  tibc: "TIBC",
  ferritin: "Ferritin",
  folate: "Folate",
  "vitamin-b12": "Vitamin B12",
  "vitamin-d": "Vitamin D",
  "omega-3-index": "Omega-3 Index",
  crp: "CRP",
  tsh: "TSH",
  "free-t4": "Free T4",
  "free-t3": "Free T3",
  cortisol: "Cortisol",
  testosterone: "Testosterone",
  "free-testosterone": "Free Testosterone",
  shbg: "SHBG",
  estradiol: "Estradiol",
  "dhea-s": "DHEA-S",
  fsh: "FSH",
  lh: "LH",
  prolactin: "Prolactin",
  psa: "PSA",
  homocysteine: "Homocysteine",
};

/** Known ids for confirm-screen dropdowns */
export const KNOWN_BIOMARKER_IDS = [
  "total-cholesterol",
  "ldl-cholesterol",
  "hdl-cholesterol",
  "triglycerides",
  "apo-b",
  "lp-a",
  "glucose-fasting",
  "hba1c",
  "insulin",
  "urea",
  "creatinine",
  "egfr",
  "uric-acid",
  "alt",
  "ast",
  "ggt",
  "alp",
  "bilirubin-total",
  "albumin",
  "hemoglobin",
  "hematocrit",
  "rbc",
  "wbc",
  "platelets",
  "mcv",
  "mch",
  "mchc",
  "rdw",
  "pdw",
  "esr",
  "esr-2h",
  "basophils",
  "eosinophils",
  "neutrophils",
  "lymphocytes",
  "monocytes",
  "bands",
  "myelocytes",
  "metamyelocytes",
  "atypical-lymphs",
  "serum-iron",
  "transferrin",
  "tibc",
  "ferritin",
  "folate",
  "vitamin-b12",
  "vitamin-d",
  "omega-3-index",
  "crp",
  "tsh",
  "free-t4",
  "free-t3",
  "cortisol",
  "testosterone",
  "free-testosterone",
  "shbg",
  "estradiol",
  "dhea-s",
  "fsh",
  "lh",
  "prolactin",
  "psa",
  "homocysteine",
] as const;
